# -*- coding: mbcs -*-
#
# Abaqus/Viewer Release 2023.HF4 replay file
# Internal Version: 2023_07_21-20.45.57 RELr425 183702
# Run by nguyenb5 on Tue Sep 17 14:36:41 2024
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=90.2552032470703, 
    height=132.6875)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from viewerModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
o2 = session.openOdb(name='phase_field_plate_3D_UEL.odb')
#: Model: C:/LocalUserData/User-data/nguyenb5/debug_phase_field_meter_many_SDV_diffusion/phase_field_plate_3D_UEL.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       9
#: Number of Node Sets:          7
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o2)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=7 )
#: Warning: The output database 'C:/LocalUserData/User-data/nguyenb5/debug_phase_field_meter_many_SDV_diffusion/phase_field_plate_3D_UEL.odb' disk file has changed.
#: 
#: The current plot operation has been canceled, re-open the file to view the results
o1 = session.openOdb(
    name='C:/LocalUserData/User-data/nguyenb5/debug_phase_field_meter_many_SDV_diffusion/phase_field_plate_3D_UEL.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o1)
#: Model: C:/LocalUserData/User-data/nguyenb5/debug_phase_field_meter_many_SDV_diffusion/phase_field_plate_3D_UEL.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       9
#: Number of Node Sets:          7
#: Number of Steps:              1
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00210645, 
    farPlane=0.00370886, width=0.001345, height=0.000629743, 
    viewOffsetX=5.63185e-05, viewOffsetY=0.000161739)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=149 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=150 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=151 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=152 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=153 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00201979, 
    farPlane=0.00379548, width=0.00188476, height=0.000882468, 
    viewOffsetX=8.59487e-05, viewOffsetY=2.78638e-05)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=202 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=202 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=202 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=202 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=202 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=202 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=203 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=204 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=205 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=206 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=207 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=208 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=208 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=208 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=208 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=208 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=208 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=208 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=208 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00212249, 
    farPlane=0.00369255, width=0.00139186, height=0.000651684, 
    viewOffsetX=7.4212e-05, viewOffsetY=7.94056e-05)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=453 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=454 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=454 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=454 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=454 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=454 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00216933, 
    farPlane=0.00364538, width=0.00112896, height=0.000528592, 
    viewOffsetX=5.41475e-05, viewOffsetY=6.11427e-05)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR23_CL_MOL', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR24_CT_MOL', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR22_C_MOL', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00228934, 
    farPlane=0.00352538, width=0.000213579, height=0.0001, 
    viewOffsetX=-2.37858e-05, viewOffsetY=-3.52471e-06)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR23_CL_MOL', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(viewOffsetX=-2.53875e-05, 
    viewOffsetY=-3.03849e-06)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=1 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=2 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=3 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=4 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=5 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=6 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=8 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=9 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=10 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=11 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=12 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=13 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=14 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=15 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=16 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=17 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=18 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=19 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=20 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=21 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=22 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=23 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=24 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=25 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=26 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=27 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=28 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=29 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=30 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=31 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=32 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=33 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=34 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=35 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=36 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=37 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=38 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=39 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=40 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=41 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=42 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=43 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=44 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=45 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=46 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=47 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=48 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=49 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=50 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=51 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=52 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=53 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=54 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=55 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=56 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=57 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=58 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=59 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=60 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=61 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=62 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=63 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=64 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=65 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=66 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=67 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=68 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=69 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=70 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=71 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=72 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=73 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=82 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=83 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=84 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=85 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=86 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=87 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=88 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=89 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=90 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=91 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=92 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=93 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=94 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=95 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=96 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=97 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=98 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=99 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=100 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=101 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=102 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=103 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=104 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=105 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=106 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=107 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=108 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=109 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=110 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=111 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=112 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=113 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=114 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=115 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=116 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=117 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=118 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=119 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=120 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=121 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=122 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=123 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=124 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=125 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=126 )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR22_C_MOL', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR24_CT_MOL', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR23_CL_MOL', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=127 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=128 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=129 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=130 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=131 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=132 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=133 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=134 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=135 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=136 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=137 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=138 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=139 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=140 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=141 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=142 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=143 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=144 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=145 )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR14_SIG_H', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(width=0.000213579, 
    height=0.0001, viewOffsetX=-2.77671e-05, viewOffsetY=-5.21934e-06)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=146 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=147 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=148 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=149 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=150 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=151 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=152 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=153 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=154 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=155 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=156 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=157 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=158 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=159 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=160 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=161 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=162 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=163 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=164 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=165 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=166 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=472 )
session.viewports['Viewport: 1'].view.setValues(viewOffsetX=-2.77794e-05, 
    viewOffsetY=-5.21933e-06)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=471 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=470 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=469 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=468 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=467 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=468 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=469 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=475 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=506 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=506 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=506 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=506 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=506 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=506 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=506 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00225129, 
    farPlane=0.00356336, width=0.000488321, height=0.000228638, 
    viewOffsetX=-2.68217e-05, viewOffsetY=-9.87555e-06)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR18_PHI', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00227957, 
    farPlane=0.00353508, width=0.000258789, height=0.000121168, 
    viewOffsetX=0.000249415, viewOffsetY=-0.00030186)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR13_EQPLAS', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00228897, 
    farPlane=0.00352569, width=0.000213579, height=0.0001, 
    viewOffsetX=-1.3528e-05, viewOffsetY=-1.61239e-05)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR14_SIG_H', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00216154, 
    farPlane=0.00365311, width=0.000988019, height=0.000462602, 
    viewOffsetX=3.07326e-05, viewOffsetY=-0.00010288)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR18_PHI', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00218534, 
    farPlane=0.00362932, width=0.000944458, height=0.000442206, 
    viewOffsetX=-3.37642e-06, viewOffsetY=-0.000202931)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=507 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=508 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=509 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=510 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=511 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=512 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=513 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=514 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=515 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=516 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=517 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=518 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=519 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=520 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=521 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00224968, 
    farPlane=0.00356496, width=0.000442394, height=0.000207134, 
    viewOffsetX=-2.72413e-06, viewOffsetY=-2.80856e-05)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=0 )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR13_EQPLAS', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=1 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=2 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=3 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=4 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=5 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=6 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=7 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=8 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=9 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=10 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=11 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=12 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=13 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=14 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=15 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=16 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=17 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=18 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=19 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=20 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=21 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=22 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=23 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=24 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=25 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=26 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=27 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=28 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=29 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=30 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=31 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=32 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=33 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=34 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=35 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=36 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=37 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=38 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=39 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=40 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=41 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=42 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=43 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00229199, 
    farPlane=0.00352386, width=0.000213579, height=0.0001, 
    viewOffsetX=-2.90456e-05, viewOffsetY=-1.66504e-05)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=44 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=45 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=46 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=47 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=48 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=49 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=50 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=51 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=52 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=53 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=54 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=55 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=56 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=57 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=58 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=59 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=60 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=61 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=62 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=63 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=64 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=65 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=66 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=67 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=68 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=69 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=70 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=71 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=72 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=73 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=74 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=75 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=76 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=77 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=78 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=79 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=80 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=81 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=82 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=83 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=84 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=85 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=86 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=87 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=88 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=89 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=90 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=91 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=92 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=93 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=94 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=95 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=96 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=97 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=98 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=99 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=100 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=101 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=102 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=103 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=104 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=105 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=106 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=107 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=108 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=109 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=110 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=111 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=112 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=113 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=114 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=115 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=116 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=117 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=118 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=119 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=120 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=121 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=122 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=123 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=124 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=125 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=126 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=127 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=128 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=129 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=130 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=131 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=132 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=133 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=134 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=135 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=136 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=137 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=138 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=139 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=140 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=141 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=142 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=143 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=144 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=145 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=146 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=147 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=148 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=149 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=150 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=151 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=152 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=153 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=154 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=155 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=156 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=157 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=158 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=159 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=160 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=161 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=162 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=163 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=164 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=165 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=166 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=167 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=168 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=169 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=170 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=171 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=172 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=173 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=174 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=175 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=176 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=177 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=178 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=179 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=180 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=181 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=182 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=183 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=184 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=185 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=186 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=187 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=188 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=189 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=190 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=191 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=192 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=193 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=194 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=590 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00225972, 
    farPlane=0.00355485, width=0.00037742, height=0.000176712, 
    viewOffsetX=0.000183971, viewOffsetY=-0.00029347)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR14_SIG_H', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00228676, 
    farPlane=0.0035278, width=0.000213579, height=0.0001, 
    viewOffsetX=1.54248e-05, viewOffsetY=-1.39026e-05)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR18_PHI', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0022653, 
    farPlane=0.00354926, width=0.000342998, height=0.000160596, 
    viewOffsetX=0.000200294, viewOffsetY=-0.000252539)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=589 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=588 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=587 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=586 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=585 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=584 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=583 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=584 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=585 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=586 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=587 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=588 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=589 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=590 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=591 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=592 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=593 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=594 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=595 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=596 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=597 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=598 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=598 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=598 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=598 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=598 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=598 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0022883, 
    farPlane=0.00352625, width=0.000213579, height=0.0001, 
    viewOffsetX=-2.68258e-05, viewOffsetY=5.51526e-06)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=599 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=600 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=601 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=602 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=603 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=604 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=643 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=643 )
session.viewports['Viewport: 1'].view.setValues(viewOffsetX=8.38318e-07, 
    viewOffsetY=-2.17205e-05)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00217572, 
    farPlane=0.00363877, width=0.000894014, height=0.000418588, 
    viewOffsetX=-7.93336e-05, viewOffsetY=0.000332737)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=644 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=645 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=646 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=647 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=648 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=649 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=650 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=651 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=652 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=653 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=654 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=655 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=656 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=657 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=658 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=659 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=660 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=661 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=662 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=663 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=664 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=665 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=666 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=667 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=668 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=669 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=684 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=684 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=685 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=686 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=687 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=688 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=689 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=690 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=691 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=692 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=693 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=694 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=695 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=696 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=697 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=698 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=699 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=700 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=700 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=700 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=700 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=700 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=700 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=700 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00211804, 
    farPlane=0.00369639, width=0.00124917, height=0.000584877, 
    viewOffsetX=0.000176608, viewOffsetY=-0.000329816)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=700 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=828 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=828 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=828 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=829 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00227203, 
    farPlane=0.00354223, width=0.000290531, height=0.00013603, 
    viewOffsetX=0.000165066, viewOffsetY=-0.000220291)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='SDV_AR9_EPS33', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=877 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=878 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00227511, 
    farPlane=0.00353908, width=0.000269222, height=0.000126053, 
    viewOffsetX=7.33921e-05, viewOffsetY=3.39011e-05)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=890 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=920 )
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.00226243, 
    farPlane=0.0035517, width=0.000389663, height=0.000182445, 
    viewOffsetX=5.37926e-05, viewOffsetY=2.80246e-05)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=985 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=985 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=985 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=985 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=985 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=985 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=985 )
session.odbs['C:/LocalUserData/User-data/nguyenb5/debug_phase_field_meter_many_SDV_diffusion/phase_field_plate_3D_UEL.odb'].close(
    )
